### ISSUE TITLE
All highlight boxes have scrollbars

### ISSUE THREAD

**Issue by tuvokki** [tuvokki/tuvokki.github.com#1]
In style.css (line: 342 according to chrome) the highlightclass always adds scrollbars to the surrounding div:

``` css
.highlight {
  background-color: #efefef;
  padding: 7px 7px 7px 10px;
  border: 1px solid #ddd;
  -moz-box-shadow: 3px 3px rgba(0, 0, 0, 0.1);
  -webkit-box-shadow: 3px 3px rgba(0, 0, 0, 0.1);
  box-shadow: 3px 3px rgba(0, 0, 0, 0.1);
  margin: 20px 0 20px 0;
  overflow: scroll;
}
```

Please fix by changing this from `scroll` to `auto`.
